name: megadepth
preprocessing:
    resize: 1024
    side: long
    square_pad: True
train_split: train_scenes_clean.txt
train_num_per_scene: 300
val_split: valid_scenes_clean.txt
val_pairs: valid_pairs.txt
test_split: test_scenes_clean.txt
min_overlap: 0.1
max_overlap: 0.7
num_overlap_bins: 3
read_depth: true
read_image: true
batch_size: 1
prefetch_factor: 4
grayscale: False
num_workers: 4
